# -*- coding: utf-8 -*-
"""Final2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YKHkLe4RvjZ2qyKJhqmCdKCU6n6BHblp
"""

# GEREKLİ KÜTÜPHANELER
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Kaggle'dan veri yükleme için (Google Colab ortamı için)
!pip install -q kaggle
from google.colab import files
files.upload()  # kaggle.json dosyasını yükleyin

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d fedesoriano/stroke-prediction-dataset
!unzip -o stroke-prediction-dataset.zip

# VERİ YÜKLEME VE ÖN İŞLEME
df = pd.read_csv("healthcare-dataset-stroke-data.csv")
df.drop("id", axis=1, inplace=True)

# Eksik bmi değerlerini medyan ile doldur
df["bmi"] = df["bmi"].fillna(df["bmi"].median())

# Gender'da "Other" olanları NaN yapıp sonra kaldır
df["gender"] = df["gender"].replace("Other", np.nan)
df.dropna(inplace=True)

# Risk seviyesi için yeni etiket oluşturma fonksiyonu
def risk_level(row):
    risk = 0
    risk += row["age"] / 100
    risk += row["hypertension"]
    risk += row["heart_disease"]
    if row["smoking_status"] == "formerly smoked":
        risk += 0.5
    elif row["smoking_status"] == "smokes":
        risk += 1
    return risk

# Risk skorunu hesapla
df["risk_score"] = df.apply(risk_level, axis=1)

# Risk seviyesini üç kategoriye ayır
df["risk_level"] = pd.cut(df["risk_score"],
                          bins=[-1, 1.5, 2.5, np.inf],
                          labels=["Low", "Medium", "High"])

# Etiketleri ve gereksiz sütunları ayır
y = df["risk_level"]
X = df.drop(["risk_level", "stroke", "risk_score"], axis=1)

# Kategorik değişkenleri one-hot encode et
X = pd.get_dummies(X, drop_first=True)

# Label encoding (Low=0, Medium=1, High=2)
le = LabelEncoder()
y = le.fit_transform(y)

# Veriyi eğitim ve test olarak ayır
X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, test_size=0.2, random_state=42
)

# Özellikleri standartlaştır
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model mimarisi fonksiyonu
def build_model(layers, num_classes):
    model = Sequential()
    model.add(tf.keras.Input(shape=(X_train.shape[1],)))
    for units in layers:
        model.add(Dense(units, activation='relu'))
        model.add(Dropout(0.3))
    model.add(Dense(num_classes, activation='softmax'))
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# MODEL 1 - Growing → Pruning
model1 = build_model([32, 16], num_classes=3)
checkpoint1 = ModelCheckpoint("model1_growing.keras", save_best_only=True)
history1 = model1.fit(X_train, y_train, validation_split=0.2, epochs=50,
                      batch_size=32, callbacks=[early_stop, checkpoint1], verbose=1)

# MODEL 2 - Pruning → Growing
model2 = build_model([128, 64, 32], num_classes=3)
checkpoint2 = ModelCheckpoint("model2_pruning.keras", save_best_only=True)
history2 = model2.fit(X_train, y_train, validation_split=0.2, epochs=50,
                      batch_size=32, callbacks=[early_stop, checkpoint2], verbose=1)

# Eğitim grafiklerini çizme fonksiyonu
def plot_history(history, title):
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Val Loss')
    plt.title(f'{title} - Loss')
    plt.legend()
    plt.subplot(1, 2, 2)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Val Accuracy')
    plt.title(f'{title} - Accuracy')
    plt.legend()
    plt.tight_layout()
    plt.show()

plot_history(history1, "Growing → Pruning")
plot_history(history2, "Pruning → Growing")

# Model değerlendirme fonksiyonu
def evaluate_model(model, X_test, y_test, label):
    y_pred = np.argmax(model.predict(X_test), axis=1)
    print(f"--- {label} ---")
    print(classification_report(y_test, y_pred, digits=4, target_names=le.classes_))
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=le.classes_, yticklabels=le.classes_)
    plt.title(f'Confusion Matrix - {label}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

evaluate_model(model1, X_test, y_test, "Growing → Pruning")
evaluate_model(model2, X_test, y_test, "Pruning → Growing")

def plot_classwise_metrics_tr(metrics_dict):
    classes = le.classes_
    model_names = list(next(iter(metrics_dict.values())).keys())
    num_classes = len(classes)
    x = np.arange(num_classes)
    width = 0.35

    # Metriklerin Türkçe karşılıkları
    metric_titles = {
        "precision": "Kesinlik (Precision)",
        "recall": "Duyarlılık (Recall)",
        "f1-score": "F1 Skoru"
    }

    for metric, model_scores in metrics_dict.items():
        plt.figure(figsize=(10, 6))
        for i, model_name in enumerate(model_names):
            scores = model_scores[model_name]
            plt.bar(x + i*width - width/2, scores, width, label=model_name)

        plt.xticks(x, classes)
        plt.ylabel(metric_titles[metric])
        plt.title(f'Sınıflara Göre {metric_titles[metric]} Karşılaştırması')
        plt.ylim(0.9, 1.01)
        plt.legend(title="Model")
        plt.grid(axis="y", linestyle="--", alpha=0.5)
        plt.tight_layout()
        plt.show()

# Türkçe grafik çizimi
plot_classwise_metrics_tr(metrics_dict)

# GEREKLİ KÜTÜPHANELER
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

from imblearn.over_sampling import SMOTE

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Google Colab ortamındaysan imblearn kur
# !pip install -q imblearn

# Kaggle verisini yükleme işlemleri
!pip install -q kaggle
from google.colab import files
files.upload()  # kaggle.json dosyasını yükle

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d fedesoriano/stroke-prediction-dataset
!unzip -o stroke-prediction-dataset.zip

# VERİ YÜKLEME VE ÖN İŞLEME
df = pd.read_csv("healthcare-dataset-stroke-data.csv")
df.drop("id", axis=1, inplace=True)

# Eksik bmi değerlerini medyan ile doldur
df["bmi"] = df["bmi"].fillna(df["bmi"].median())

# Gender'da "Other" olanları NaN yapıp sonra kaldır
df["gender"] = df["gender"].replace("Other", np.nan)
df.dropna(inplace=True)

# Risk seviyesi için yeni etiket oluşturma fonksiyonu
def risk_level(row):
    risk = 0
    risk += row["age"] / 100
    risk += row["hypertension"]
    risk += row["heart_disease"]
    if row["smoking_status"] == "formerly smoked":
        risk += 0.5
    elif row["smoking_status"] == "smokes":
        risk += 1
    return risk

# Risk skorunu hesapla
df["risk_score"] = df.apply(risk_level, axis=1)

# Risk seviyesini üç kategoriye ayır
df["risk_level"] = pd.cut(df["risk_score"],
                          bins=[-1, 1.5, 2.5, np.inf],
                          labels=["Low", "Medium", "High"])

# Etiketleri ve gereksiz sütunları ayır
y = df["risk_level"]
X = df.drop(["risk_level", "stroke", "risk_score"], axis=1)

# Kategorik değişkenleri one-hot encode et
X = pd.get_dummies(X, drop_first=True)

# Label encoding (Low=0, Medium=1, High=2)
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Veri dengesizliğini SMOTE ile düzeltelim
sm = SMOTE(random_state=42)
X_resampled, y_resampled = sm.fit_resample(X, y_encoded)

# Veriyi eğitim ve test olarak ayır (stratify gerekmez çünkü SMOTE sonrası dengeli)
X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42
)

# Özellikleri standartlaştır
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model mimarisi fonksiyonu
def build_model(layers, num_classes):
    model = Sequential()
    model.add(tf.keras.Input(shape=(X_train.shape[1],)))
    for units in layers:
        model.add(Dense(units, activation='relu'))
        model.add(Dropout(0.3))
    model.add(Dense(num_classes, activation='softmax'))
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# MODEL 1 - Growing → Pruning
model1 = build_model([32, 16], num_classes=3)
checkpoint1 = ModelCheckpoint("model1_growing.keras", save_best_only=True)
history1 = model1.fit(X_train, y_train, validation_split=0.2, epochs=50,
                      batch_size=32, callbacks=[early_stop, checkpoint1], verbose=1)

# MODEL 2 - Pruning → Growing
model2 = build_model([128, 64, 32], num_classes=3)
checkpoint2 = ModelCheckpoint("model2_pruning.keras", save_best_only=True)
history2 = model2.fit(X_train, y_train, validation_split=0.2, epochs=50,
                      batch_size=32, callbacks=[early_stop, checkpoint2], verbose=1)

# Eğitim grafiklerini çizme fonksiyonu
def plot_history(history, title):
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Val Loss')
    plt.title(f'{title} - Kayıp (Loss)')
    plt.legend()
    plt.subplot(1, 2, 2)
    plt.plot(history.history['accuracy'], label='Train Doğruluk (Accuracy)')
    plt.plot(history.history['val_accuracy'], label='Val Doğruluk (Accuracy)')
    plt.title(f'{title} - Doğruluk (Accuracy)')
    plt.legend()
    plt.tight_layout()
    plt.show()

plot_history(history1, "Growing → Pruning")
plot_history(history2, "Pruning → Growing")

# Model değerlendirme fonksiyonu
def evaluate_model(model, X_test, y_test, label):
    y_pred = np.argmax(model.predict(X_test), axis=1)
    print(f"--- {label} ---")
    print(classification_report(y_test, y_pred, digits=4, target_names=le.classes_))
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=le.classes_, yticklabels=le.classes_)
    plt.title(f'Karışıklık Matrisi - {label}')
    plt.xlabel('Tahmin Edilen')
    plt.ylabel('Gerçek')
    plt.show()

evaluate_model(model1, X_test, y_test, "Growing → Pruning")
evaluate_model(model2, X_test, y_test, "Pruning → Growing")